"use client"

import { useEffect, useRef, useState } from "react"
import {
  Smartphone,
  Tablet,
  Monitor,
  Wifi,
  WifiOff,
  Globe,
  Sun,
  Moon,
  Copy,
  Check,
  ExternalLink,
  FolderTree,
  Code2,
  Terminal,
  GripHorizontal,
  File,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { cn } from "@/lib/utils"
import {
  MOCK_TERMINAL_LOGS,
  MOCK_HTML_PREVIEWS,
  type PromptType,
} from "./mock-previews"

// ─── Types ──────────────────────────────────────────────────────────────

interface PreviewPanelProps {
  previewUrl: string | null
  isLoading: boolean
  promptType?: PromptType
}

type Device = "mobile" | "tablet" | "desktop"
type Network = "wifi" | "4g" | "offline"
type Theme = "light" | "dark"

// ─── Mock Data ──────────────────────────────────────────────────────────

interface FileEntry {
  name: string
  type: "file" | "folder"
  children?: FileEntry[]
}

const FILE_TREE: FileEntry[] = [
  {
    name: "docker-compose.yml",
    type: "file",
  },
  {
    name: "prisma",
    type: "folder",
    children: [
      { name: "schema.prisma", type: "file" },
    ],
  },
  {
    name: "src",
    type: "folder",
    children: [
      {
        name: "app",
        type: "folder",
        children: [
          { name: "layout.tsx", type: "file" },
          { name: "page.tsx", type: "file" },
        ],
      },
      {
        name: "components",
        type: "folder",
        children: [
          {
            name: "ui",
            type: "folder",
            children: [{ name: "button.tsx", type: "file" }],
          },
        ],
      },
      {
        name: "lib",
        type: "folder",
        children: [
          { name: "auth.ts", type: "file" },
          { name: "db.ts", type: "file" },
        ],
      },
    ],
  },
  { name: "package.json", type: "file" },
]

const MOCK_FILES: Record<string, string> = {
  "docker-compose.yml": `version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: omnistack`,
  "schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(uuid())
  email String @unique
  name  String
  role  Role   @default(USER)
}

enum Role {
  ADMIN
  USER
  VIEWER
}`,
  "package.json": `{
  "name": "omnistack-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.3.x",
    "react": "^19.0.0"
  }
}`,
  "layout.tsx": `import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "OmniStack App",
  description: "Generated by AI Architect",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`,
  "page.tsx": `export default function Home() {
  return (
    <main className="flex min-h-screen items-center justify-center">
      <h1 className="text-4xl font-bold">Hello World</h1>
    </main>
  )
}`,
  "button.tsx": `"use client"

import { cn } from "@/lib/utils"

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "outline"
  size?: "sm" | "md" | "lg"
}

export function Button({ className, variant = "default", ...props }: ButtonProps) {
  return (
    <button
      className={cn(
        "rounded-md px-4 py-2 font-medium transition-colors",
        variant === "default" && "bg-primary text-white hover:bg-primary/90",
        variant === "outline" && "border border-input bg-background hover:bg-muted",
        className
      )}
      {...props}
    />
  )
}`,
  "auth.ts": `import jwt from "jsonwebtoken"

export function verifyToken(token: string) {
  return jwt.verify(token, process.env.JWT_SECRET!)
}

export function signToken(payload: object) {
  return jwt.sign(payload, process.env.JWT_SECRET!, { expiresIn: "7d" })
}`,
  "db.ts": `import { PrismaClient } from "@prisma/client"

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient }

export const prisma = globalForPrisma.prisma || new PrismaClient()

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma`,
}

const TERMINAL_LINES = [
  { text: "> npm install", delay: 400 },
  { text: "> prisma generate", delay: 300 },
  { text: "> npm run build", delay: 500 },
  { text: "Build successful", delay: 200 },
  { text: "-> Deploying to preview environment...", delay: 600 },
  { text: "Live at pr-ai-8f7d.omnistack.app", delay: 300 },
]

// ─── Helper: Render file tree recursively ───────────────────────────────

function TreeNode({
  entries,
  depth,
  selectedFile,
  onSelect,
}: {
  entries: FileEntry[]
  depth: number
  selectedFile: string | null
  onSelect: (path: string) => void
}) {
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})

  const toggleFolder = (name: string) => {
    setExpanded((prev) => ({ ...prev, [name]: !prev[name] }))
  }

  return (
    <>
      {entries.map((entry) => {
        const isFolder = entry.type === "folder"
        const isExpanded = expanded[entry.name] ?? (depth < 1)
        const fullPath = entry.name

        return (
          <div key={fullPath}>
            <button
              onClick={() => {
                if (isFolder) {
                  toggleFolder(entry.name)
                } else {
                  onSelect(fullPath)
                }
              }}
              className={cn(
                "flex w-full items-center gap-1.5 rounded-md px-2 py-0.5 text-left text-xs font-mono transition-colors",
                selectedFile === fullPath
                  ? "bg-accent text-accent-foreground"
                  : "text-muted-foreground hover:bg-muted hover:text-foreground"
              )}
            >
              {isFolder ? (
                <FolderTree className="h-3 w-3 shrink-0 text-muted-foreground" />
              ) : (
                <File className="h-3 w-3 shrink-0 text-muted-foreground" />
              )}
              <span>{entry.name}</span>
            </button>
            {isFolder && isExpanded && entry.children && (
              <div className="ml-3">
                <TreeNode
                  entries={entry.children}
                  depth={depth + 1}
                  selectedFile={selectedFile}
                  onSelect={(childPath) => onSelect(`${entry.name}/${childPath}`)}
                />
              </div>
            )}
          </div>
        )
      })}
    </>
  )
}

// ─── Network Dropdown (manual, no radix) ────────────────────────────────

function NetworkDropdown({
  network,
  onChange,
}: {
  network: Network
  onChange: (n: Network) => void
}) {
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  const options: { value: Network; label: string; icon: typeof Wifi }[] = [
    { value: "wifi", label: "WiFi (No throttle)", icon: Wifi },
    { value: "4g", label: "4G (Throttle)", icon: Globe },
    { value: "offline", label: "Offline (Block)", icon: WifiOff },
  ]

  const current = options.find((o) => o.value === network)!

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener("mousedown", handleClickOutside)
    return () => document.removeEventListener("mousedown", handleClickOutside)
  }, [])

  return (
    <div className="relative" ref={ref}>
      <Button
        variant="ghost"
        size="sm"
        onClick={() => setOpen(!open)}
        className="gap-1.5 text-xs"
      >
        <current.icon className="h-3.5 w-3.5" />
        <span className="hidden sm:inline">{current.label}</span>
      </Button>
      {open && (
        <div className="absolute top-full left-0 z-50 mt-1 w-48 rounded-lg border bg-popover p-1 shadow-md">
          {options.map((opt) => (
            <button
              key={opt.value}
              onClick={() => {
                onChange(opt.value)
                setOpen(false)
              }}
              className={cn(
                "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-xs transition-colors",
                network === opt.value
                  ? "bg-accent text-accent-foreground"
                  : "text-muted-foreground hover:bg-muted hover:text-foreground"
              )}
            >
              <opt.icon className="h-3.5 w-3.5" />
              {opt.label}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

// ─── Loading Skeleton (Terminal-style) ──────────────────────────────────

function LoadingSkeleton({ promptType }: { promptType?: PromptType }) {
  const [visibleLines, setVisibleLines] = useState(0)
  const lines = promptType
    ? MOCK_TERMINAL_LOGS[promptType] || TERMINAL_LINES
    : TERMINAL_LINES

  useEffect(() => {
    let step = 0
    let cancelled = false
    const delays = lines.map((l) => l.delay)
    function scheduleNext() {
      if (cancelled || step >= lines.length) return
      const d = Math.max(delays[step] || 400, 180)
      setTimeout(() => {
        if (cancelled) return
        step += 1
        setVisibleLines(step)
        scheduleNext()
      }, d)
    }
    scheduleNext()
    return () => {
      cancelled = true
    }
  }, [lines])

  return (
    <div className="flex h-full flex-col items-center justify-center p-8">
      <div className="w-full max-w-lg rounded-lg border border-zinc-800 bg-zinc-950 p-4 shadow-lg">
        <div className="mb-3 flex gap-1.5">
          <div className="h-3 w-3 rounded-full bg-red-500" />
          <div className="h-3 w-3 rounded-full bg-yellow-500" />
          <div className="h-3 w-3 rounded-full bg-green-500" />
        </div>
        <div className="font-mono text-xs">
          <div className="text-zinc-500">Building container...</div>
          {lines.slice(0, visibleLines).map((line, i) => (
            <div key={i} className="mt-1 flex items-center gap-2">
              {line.text ? (
                <>
                  <span className="text-blue-400">[</span>
                  <span className="text-zinc-500">
                    {String(14).padStart(2, "0")}:{String(32).padStart(2, "0")}:
                    {String(i * 2 + 1).padStart(2, "0")}
                  </span>
                  <span className="text-blue-400">]</span>
                  <span className={cn(
                    "text-zinc-300",
                    line.text.includes("✅") && "text-green-400",
                    line.text.includes("$") && "text-blue-400"
                  )}>
                    {line.text}
                  </span>
                </>
              ) : (
                <span>&nbsp;</span>
              )}
            </div>
          ))}
          {visibleLines < lines.length && (
            <div className="mt-1 flex items-center gap-2">
              <span className="text-blue-400">[</span>
              <span className="text-zinc-500">
                {String(14).padStart(2, "0")}:{String(32).padStart(2, "0")}:
                {String(visibleLines * 2 + 1).padStart(2, "0")}
              </span>
              <span className="text-blue-400">]</span>
              <span className="animate-pulse text-blue-400">...</span>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Empty State ────────────────────────────────────────────────────────

function EmptyState() {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-3 text-muted-foreground">
      <Code2 className="h-10 w-10 opacity-40" />
      <p className="text-sm">Generate an app to see preview</p>
    </div>
  )
}

// ─── Main Component ─────────────────────────────────────────────────────

export function PreviewPanel({ previewUrl, isLoading, promptType }: PreviewPanelProps) {
  const [device, setDevice] = useState<Device>("desktop")
  const [network, setNetwork] = useState<Network>("wifi")
  const [iframeTheme, setIframeTheme] = useState<Theme>("light")
  const [drawerOpen, setDrawerOpen] = useState(true)
  const [activeTab, setActiveTab] = useState("files")
  const [selectedFile, setSelectedFile] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const deviceWidth = {
    mobile: 375,
    tablet: 768,
    desktop: 100,
  }

  const handleCopyUrl = () => {
    const url = previewUrl || "pr-ai-8f7d.omnistack.app"
    navigator.clipboard.writeText(url)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="flex h-full flex-col border-l bg-background">
      {/* ── Simulator Toolbar ─────────────────────────────────────────── */}
      <div className="flex items-center gap-1 border-b px-3 py-1.5">
        {/* Device Toggle */}
        <div className="flex items-center gap-0.5 rounded-md border p-0.5">
          {([
            { value: "mobile" as Device, icon: Smartphone, label: "Mobile" },
            { value: "tablet" as Device, icon: Tablet, label: "Tablet" },
            { value: "desktop" as Device, icon: Monitor, label: "Desktop" },
          ]).map((d) => (
            <Button
              key={d.value}
              variant="ghost"
              size="icon-xs"
              onClick={() => setDevice(d.value)}
              className={cn(
                device === d.value &&
                  "bg-primary text-primary-foreground hover:bg-primary/80"
              )}
              title={d.label}
            >
              <d.icon className="h-3.5 w-3.5" />
            </Button>
          ))}
        </div>

        {/* Network Simulator */}
        <NetworkDropdown network={network} onChange={setNetwork} />

        {/* Theme Toggle */}
        <Button
          variant="ghost"
          size="icon-xs"
          onClick={() =>
            setIframeTheme(iframeTheme === "light" ? "dark" : "light")
          }
          title={`Switch to ${iframeTheme === "light" ? "dark" : "light"} mode`}
        >
          {iframeTheme === "light" ? (
            <Sun className="h-3.5 w-3.5" />
          ) : (
            <Moon className="h-3.5 w-3.5" />
          )}
        </Button>

        {/* Spacer */}
        <div className="flex-1" />

        {/* URL Bar */}
        <div className="flex items-center gap-1 rounded-md border bg-muted/50 px-2 py-1">
          <span className="font-mono text-xs text-muted-foreground">
            {previewUrl || "pr-ai-8f7d.omnistack.app"}
          </span>
          <Button
            variant="ghost"
            size="icon-xs"
            onClick={handleCopyUrl}
            title="Copy URL"
          >
            {copied ? (
              <Check className="h-3 w-3 text-green-500" />
            ) : (
              <Copy className="h-3 w-3" />
            )}
          </Button>
          <Button
            variant="ghost"
            size="icon-xs"
            title="Open in new tab"
            onClick={() => {
              if (previewUrl) window.open(previewUrl, "_blank")
            }}
          >
            <ExternalLink className="h-3 w-3" />
          </Button>
        </div>
      </div>

      {/* ── Live Preview Canvas ───────────────────────────────────────── */}
      <div className="flex-1 overflow-auto bg-muted/30 p-4">
        {isLoading ? (
          <LoadingSkeleton promptType={promptType} />
        ) : !previewUrl ? (
          <EmptyState />
        ) : (
          <div className="flex h-full items-start justify-center">
            <div
              className={cn(
                "relative overflow-hidden rounded-lg border shadow-lg transition-all duration-300",
                network === "offline" && "pointer-events-none"
              )}
              style={{
                width:
                  device === "desktop"
                    ? "100%"
                    : `${deviceWidth[device]}px`,
                maxWidth: "100%",
                height: "100%",
                maxHeight: "calc(100vh - 200px)",
              }}
            >
              {/* iframe border / chrome */}
              <div className="flex items-center gap-1.5 border-b bg-muted/50 px-3 py-1.5">
                <div className="flex gap-1">
                  <div className="h-2.5 w-2.5 rounded-full bg-red-400" />
                  <div className="h-2.5 w-2.5 rounded-full bg-yellow-400" />
                  <div className="h-2.5 w-2.5 rounded-full bg-green-400" />
                </div>
                <span className="ml-2 flex-1 rounded bg-background/50 px-2 py-0.5 text-center font-mono text-[10px] text-muted-foreground">
                  {previewUrl}
                </span>
              </div>

              {/* iframe — use srcdoc for mock previews */}
              {promptType && MOCK_HTML_PREVIEWS[promptType] ? (
                <iframe
                  srcDoc={MOCK_HTML_PREVIEWS[promptType]}
                  title="App Preview"
                  className="h-full w-full border-0"
                  sandbox="allow-scripts"
                  style={{
                    filter:
                      iframeTheme === "dark"
                        ? "invert(0.88) hue-rotate(180deg)"
                        : undefined,
                  }}
                />
              ) : (
                <iframe
                  src={previewUrl}
                  title="App Preview"
                  className="h-full w-full border-0"
                  sandbox="allow-scripts allow-same-origin"
                  style={{
                    filter:
                      iframeTheme === "dark"
                        ? "invert(0.88) hue-rotate(180deg)"
                        : undefined,
                  }}
                />
              )}

              {/* Offline overlay */}
              {network === "offline" && (
                <div className="absolute inset-0 flex flex-col items-center justify-center bg-background/80 backdrop-blur-sm">
                  <WifiOff className="mb-2 h-8 w-8 text-muted-foreground" />
                  <p className="text-sm font-medium text-muted-foreground">
                    No connection
                  </p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* ── Bottom Drawer ─────────────────────────────────────────────── */}
      <div
        className={cn(
          "border-t transition-[height] duration-200",
          drawerOpen ? "h-[40%]" : "h-8"
        )}
      >
        {/* Drawer handle */}
        <button
          onClick={() => setDrawerOpen(!drawerOpen)}
          className="flex h-8 w-full items-center justify-center gap-2 border-b bg-muted/30 transition-colors hover:bg-muted/50"
        >
          <GripHorizontal className="h-4 w-4 text-muted-foreground" />
          <span className="text-xs text-muted-foreground">
            {drawerOpen ? "Collapse" : "Expand"}
          </span>
        </button>

        {/* Drawer content */}
        {drawerOpen && (
          <div className="flex h-[calc(100%-2rem)] flex-col overflow-hidden">
            <Tabs
              value={activeTab}
              onValueChange={(val) => {
                if (val) setActiveTab(val)
              }}
              className="flex flex-1 flex-col overflow-hidden"
            >
              <div className="flex items-center border-b px-2">
                <TabsList variant="line" className="h-9">
                  <TabsTrigger value="files" className="gap-1.5 text-xs">
                    <FolderTree className="h-3.5 w-3.5" />
                    Files
                  </TabsTrigger>
                  <TabsTrigger value="code" className="gap-1.5 text-xs">
                    <Code2 className="h-3.5 w-3.5" />
                    Code
                  </TabsTrigger>
                  <TabsTrigger value="terminal" className="gap-1.5 text-xs">
                    <Terminal className="h-3.5 w-3.5" />
                    Terminal
                  </TabsTrigger>
                </TabsList>
                <div className="flex-1" />
                <Button
                  variant="ghost"
                  size="sm"
                  className="gap-1.5 text-xs text-muted-foreground"
                >
                  <Code2 className="h-3.5 w-3.5" />
                  Open in Cloud IDE
                </Button>
              </div>

              {/* Files Tab */}
              <TabsContent value="files" className="overflow-auto p-2">
                <div className="font-mono text-xs">
                  <TreeNode
                    entries={FILE_TREE}
                    depth={0}
                    selectedFile={selectedFile}
                    onSelect={(path) => setSelectedFile(path)}
                  />
                </div>
              </TabsContent>

              {/* Code Tab */}
              <TabsContent
                value="code"
                className="overflow-auto font-mono text-xs"
              >
                {selectedFile ? (
                  <pre className="p-4 text-foreground">
                    {MOCK_FILES[selectedFile] || `// No content for ${selectedFile}`}
                  </pre>
                ) : (
                  <div className="flex h-full items-center justify-center p-8 text-muted-foreground">
                    Select a file to view its content
                  </div>
                )}
              </TabsContent>

              {/* Terminal Tab */}
              <TabsContent
                value="terminal"
                className="overflow-auto bg-zinc-950 p-4 font-mono text-xs"
              >
                <div className="space-y-1">
                  {[
                    "[14:32:01] > npm install",
                    "[14:32:03] > prisma generate",
                    "[14:32:05] > Generated Prisma Client",
                    "[14:32:06] > npm run build",
                    "[14:32:12] > Build successful",
                    "[14:32:13] -> Deploying to preview environment...",
                    "[14:32:15] > Live at pr-ai-8f7d.omnistack.app",
                  ].map((line, i) => (
                    <div key={i} className="text-zinc-300">
                      {line}
                    </div>
                  ))}
                  <div className="mt-2 flex items-center gap-1">
                    <span className="text-blue-400">$</span>
                    <span className="animate-pulse text-blue-400">_</span>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        )}
      </div>
    </div>
  )
}
